# Generated by Django 4.2.4 on 2023-08-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='_review',
            new_name='mreview',
        ),
    ]
